const menu = {
    list() {
        return [
    {
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"管理员管理",
                        "menuJump":"列表",
                        "tableName":"users"
                    }
                ],
                "menu":"管理员管理"
            }
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"小区管理员管理",
			            "menuJump":"列表",
			            "tableName":"xiaoquguanli"
			        }
			    ],
			    "menu":"小区管理员管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"采购员管理",
			            "menuJump":"列表",
			            "tableName":"yonghu"
			        }
			    ],
			    "menu":"采购员管理"
			}
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "报表",
                            "删除"
                        ],
                        "menu":"物资管理",
                        "menuJump":"列表",
                        "tableName":"wuzi"
                    }
                ],
                "menu":"物资管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "审核",
                            "删除"
                        ],
                        "menu":"物资采购管理",
                        "menuJump":"列表",
                        "tableName":"wuzicaigou"
                    }
                ],
                "menu":"物资采购管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
			                "新增",
                            "删除"
                        ],
                        "menu":"物资调配管理",
                        "menuJump":"列表",
                        "tableName":"wuzidiaopei"
                    }
                ],
                "menu":"物资调配管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"物资捐赠管理",
                        "menuJump":"列表",
                        "tableName":"wuzijuanzeng"
                    }
                ],
                "menu":"物资捐赠管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
			                "新增",
                            "删除"
                        ],
                        "menu":"物资派发管理",
                        "menuJump":"列表",
                        "tableName":"wuzipaifa"
                    }
                ],
                "menu":"物资派发管理"
            }
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "删除"
			            ],
			            "menu":"物资领用归还管理",
			            "menuJump":"列表",
			            "tableName":"lingyongguihuan"
			        }
			    ],
			    "menu":"物资领用归还管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "删除"
			            ],
			            "menu":"需求收集管理",
			            "menuJump":"列表",
			            "tableName":"xuqiutongji"
			        }
			    ],
			    "menu":"需求收集管理"
			}
			
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"自愿者管理",
			            "menuJump":"列表",
			            "tableName":"zhiyaunzhe"
			        }
			    ],
			    "menu":"自愿者管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"志愿者调派管理",
			            "menuJump":"列表",
			            "tableName":"zhiyuanzhepaiqian"
			        }
			    ],
			    "menu":"志愿者调派管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "删除",
			                "修改"
			            ],
			            "menu":"公告类型管理",
			            "menuJump":"列表",
			            "tableName":"dictionaryNews"
			        }
			        ,
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "删除",
			                "修改"
			            ],
			            "menu":"物资类型管理",
			            "menuJump":"列表",
			            "tableName":"dictionaryWuzi"
			        }
			        ,
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "删除",
			                "修改"
			            ],
			            "menu":"派遣类型管理",
			            "menuJump":"列表",
			            "tableName":"dictionaryZhiyuanzhepaiqian"
			        }
			    ],
			    "menu":"基础数据管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"公告信息管理",
			            "menuJump":"列表",
			            "tableName":"news"
			        }
			    ],
			    "menu":"公告信息管理"
			}
            /*,{
			    "child":[
			        {
			            "buttons":[
			                "查看"
			            ],
			            "menu":"数据备份",
			            "menuJump":"列表",
			            "tableName":"beifen"
			        },
					{
					    "buttons":[
					        "查看"
					    ],
					    "menu":"数据还原",
					    "menuJump":"列表",
					    "tableName":"huanyuan"
					}
			    ],
			    "menu":"数据库管理"
			}*/
        ],
        "frontMenu":[],
        "hasBackLogin":"是",
        "hasBackRegister":"否",
        "hasFrontLogin":"否",
        "hasFrontRegister":"否",
        "roleName":"管理员",
        "tableName":"users"
    },
	{
	    "backMenu":[
	        {
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"采购员管理",
			            "menuJump":"列表",
			            "tableName":"yonghu"
			        }
			    ],
			    "menu":"采购员管理"
			}
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"物资管理",
	                    "menuJump":"列表",
	                    "tableName":"wuzi"
	                }
	            ],
	            "menu":"物资管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看",
	                        "审核"
	                    ],
	                    "menu":"物资采购管理",
	                    "menuJump":"列表",
	                    "tableName":"wuzicaigou"
	                }
	            ],
	            "menu":"物资采购管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"物资调配管理",
	                    "menuJump":"列表",
	                    "tableName":"wuzidiaopei"
	                }
	            ],
	            "menu":"物资调配管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看",
			                "新增",
	                        "删除"
	                    ],
	                    "menu":"物资捐赠管理",
	                    "menuJump":"列表",
	                    "tableName":"wuzijuanzeng"
	                }
	            ],
	            "menu":"物资捐赠管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"物资派发管理",
	                    "menuJump":"列表",
	                    "tableName":"wuzipaifa"
	                }
	            ],
	            "menu":"物资派发管理"
	        }
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "删除"
			            ],
			            "menu":"物资领用归还管理",
			            "menuJump":"列表",
			            "tableName":"lingyongguihuan"
			        }
			    ],
			    "menu":"物资领用归还管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "删除"
			            ],
			            "menu":"需求收集管理",
			            "menuJump":"列表",
			            "tableName":"xuqiutongji"
			        }
			    ],
			    "menu":"需求收集管理"
			}
			
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"自愿者管理",
			            "menuJump":"列表",
			            "tableName":"zhiyaunzhe"
			        }
			    ],
			    "menu":"自愿者管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"志愿者调派管理",
			            "menuJump":"列表",
			            "tableName":"zhiyuanzhepaiqian"
			        }
			    ],
			    "menu":"志愿者调派管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看"
			            ],
			            "menu":"公告信息管理",
			            "menuJump":"列表",
			            "tableName":"news"
			        }
			    ],
			    "menu":"公告信息管理"
			}

	    ],
	    "frontMenu":[],
	    "hasBackLogin":"是",
	    "hasBackRegister":"否",
	    "hasFrontLogin":"否",
	    "hasFrontRegister":"否",
	    "roleName":"小区管理",
	    "tableName":"xiaoquguanli"
	},
	{
	    "backMenu":[
	        {
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"物资管理",
	                    "menuJump":"列表",
	                    "tableName":"wuzi"
	                }
	            ],
	            "menu":"物资管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看",
	                        "新增",
	                        "入库"
	                    ],
	                    "menu":"物资采购管理",
	                    "menuJump":"列表",
	                    "tableName":"wuzicaigou"
	                }
	            ],
	            "menu":"物资采购管理"
	        }
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看"
			            ],
			            "menu":"公告信息管理",
			            "menuJump":"列表",
			            "tableName":"news"
			        }
			    ],
			    "menu":"公告信息管理"
			}
	
	    ],
	    "frontMenu":[],
	    "hasBackLogin":"是",
	    "hasBackRegister":"否",
	    "hasFrontLogin":"否",
	    "hasFrontRegister":"否",
	    "roleName":"采购员",
	    "tableName":"yonghu"
	}
]
    }
}
export default menu;
